# Generated by Django 5.2.17 on 2026-09-10 12:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default MRP'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default purchase price'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default selling price (GST inclusive)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='default GST rate (%)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Blank inherits the product's default MRP.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='MRP override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Blank inherits the product's default purchase price.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='purchase price override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Blank inherits the product's default selling price.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='selling price override (GST inclusive)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Blank inherits the product's default GST rate.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='GST rate override (%)'),
        ),
    ]
