# Generated by Django 5.2.17 on 2026-09-10 13:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_remove_productvariant_discount_product_mrp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerializedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(editable=False, max_length=64, unique=True)),
                ('sequence', models.PositiveIntegerField(editable=False, help_text='Per-variant counter behind the serial number.')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_TRANSIT', 'In transit'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], db_index=True, default='GENERATED', max_length=16)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='inventory.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serialized_units', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SerializedUnitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.location')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.serializedunit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serializedunit',
            constraint=models.UniqueConstraint(fields=('variant', 'sequence'), name='uniq_sequence_per_variant'),
        ),
    ]
