# Generated by Django 5.2.17 on 2026-09-11 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_sale_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AMAZON_FEES', 'Amazon fees'), ('SHIPPING', 'Shipping'), ('COURIER', 'Courier'), ('PACKAGING', 'Packaging'), ('ADVERTISING', 'Advertising'), ('MANUFACTURING', 'Manufacturing'), ('RAW_MATERIALS', 'Raw materials'), ('OFFLINE_EXPENSES', 'Offline expenses'), ('OTHER', 'Other expenses')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_channel', models.ForeignKey(blank=True, help_text='Optional -- which channel this expense belongs to, for channel-wise reporting. Leave blank for a general/business-wide expense.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.saleschannel')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
