# Generated by Django 5.2.17 on 2026-09-12 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SALES', 'Sales'), ('INVENTORY', 'Inventory'), ('SERIAL_NUMBERS', 'Serial numbers'), ('SERIAL_NUMBER_HISTORY', 'Serial number history'), ('PRODUCTS', 'Products'), ('FINANCIAL', 'Financial')], max_length=24)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel')], max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='The query params the export was requested with (date_from/date_to/channel/location/group_by, per report type).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('file', models.FileField(blank=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
