# Generated by Django 5.2.17 on 2026-09-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_labelbatch_labelbatchitem'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='sales.saleline')),
                ('serialized_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_line_unit', to='products.serializedunit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
