# Generated by Django 5.2.17 on 2026-09-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_salelineunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Who this sale is for. Null is a true walk-in with no customer record at all (HEXAGARE_FEATURES.md section 30) -- distinct from a Customer row with type=WALK_IN, which is a lightweight name/phone on record without full registration.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer'),
        ),
    ]
