# Generated by Django 5.2.17 on 2026-09-11 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_labelbatch_labelbatchitem'),
        ('sales', '0002_salelineunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(choices=[('REFERRAL', 'Referral fee'), ('CLOSING', 'Closing fee'), ('FULFILLMENT', 'Fulfillment fee'), ('SHIPPING', 'Shipping / courier'), ('ADVERTISING', 'Advertising'), ('OTHER', 'Other charges')], max_length=16)),
                ('fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of taxable value'), ('FIXED', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percentage (0-100) when fee_type=PERCENTAGE, else a fixed rupee amount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Blank = open-ended.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_category', models.ForeignKey(blank=True, help_text='Leave blank to apply to every category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_fee_configs', to='products.category')),
                ('applicable_product', models.ForeignKey(blank=True, help_text='Leave blank to apply to every product. Takes precedence over category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_fee_configs', to='products.product')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_fee_configs', to='sales.saleschannel')),
            ],
            options={
                'ordering': ['fee_name', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AmazonImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='amazon-imports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('PARTIAL', 'Partially imported'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_updated', models.PositiveIntegerField(default=0)),
                ('orders_skipped', models.PositiveIntegerField(default=0)),
                ('orders_failed', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, help_text='Set only on a whole-batch failure (e.g. an unreadable file).')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AmazonSkuMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_sku', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amazon_sku_mappings', to='products.productvariant')),
            ],
            options={
                'ordering': ['amazon_sku'],
            },
        ),
        migrations.CreateModel(
            name='AmazonOrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('referral_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fulfillment_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('advertising_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_settlements', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amazon_settlements', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('sale', 'sku'), name='uniq_amazon_settlement_sale_sku')],
            },
        ),
    ]
