# Generated by Django 5.2.17 on 2026-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('warehouse', 'Warehouse'), ('marketplace', 'Marketplace'), ('retail', 'Retail'), ('other', 'Other')], default='other', help_text='Classification for reporting only -- do not branch on it.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
