# Generated by Django 5.2.17 on 2026-09-10 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0003_serializedunit_serializedunitevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='inventory.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='products.productvariant')),
            ],
            options={
                'ordering': ['variant_id', 'location_id', 'status'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'location', 'status'), name='uniq_balance_bucket')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Groups the rows produced by one operation (the -1/+1 pair of a move).')),
                ('kind', models.CharField(choices=[('OPENING', 'Opening stock'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release reservation'), ('SALE', 'Sale'), ('RETURN', 'Customer return'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('RESTORE', 'Restore to available'), ('CANCEL', 'Allocation cancelled'), ('ADJUSTMENT', 'Manual adjustment')], max_length=16)),
                ('status', models.CharField(help_text='The stock bucket this row moves -- a SerializedUnit.Status value.', max_length=16)),
                ('quantity', models.IntegerField(help_text='Signed change to (variant, location, status): +in / -out. Never 0.')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.location')),
                ('serialized_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.serializedunit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', 'location', 'status'], name='inventory_i_variant_1407dc_idx'), models.Index(fields=['reference'], name='inventory_i_referen_6e561a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='Low-stock at or below this level; out-of-stock at 0.')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Overstock at or above this level. Blank = no ceiling.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text="Blank = applies to the variant's total across all locations.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_policies', to='inventory.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_policies', to='products.productvariant')),
            ],
            options={
                'verbose_name_plural': 'stock level policies',
                'ordering': ['variant_id', 'location_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('variant', 'location'), name='uniq_policy_per_variant_location'), models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('variant',), name='uniq_global_policy_per_variant')],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('serialized_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='products.serializedunit')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('transfer', 'serialized_unit'), name='uniq_unit_per_transfer')],
            },
        ),
    ]
