# Generated by Django 5.2.17 on 2026-09-12 10:21

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('file', models.FileField(blank=True, upload_to='backups/')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'backup job',
                'verbose_name_plural': 'backup jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('default_tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-filled as the default GST rate (%) on a new product; not enforced.', max_digits=5, null=True)),
                ('sku_prefix', models.CharField(blank=True, help_text='Blank falls back to HEXAGARE_SKU_PREFIX.', max_length=16)),
                ('serial_prefix', models.CharField(blank=True, help_text='Blank falls back to HEXAGARE_SERIAL_PREFIX.', max_length=16)),
                ('serial_padding', models.PositiveSmallIntegerField(blank=True, help_text='Blank falls back to HEXAGARE_SERIAL_PADDING.', null=True)),
                ('invoice_prefix', models.CharField(blank=True, help_text='Blank falls back to HEXAGARE_INVOICE_PREFIX.', max_length=16)),
                ('invoice_padding', models.PositiveSmallIntegerField(blank=True, help_text='Blank falls back to HEXAGARE_INVOICE_PADDING.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business settings',
                'verbose_name_plural': 'business settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('product.created', 'Product created'), ('product.updated', 'Product/variant/SKU/price updated'), ('product.deleted', 'Product deleted'), ('serial.created', 'Serial number / unit created'), ('barcode.generated', 'Barcode / label batch generated'), ('stock.changed', 'Stock adjusted'), ('status.changed', 'Unit status changed'), ('location.created', 'Location created'), ('location.updated', 'Location updated'), ('location.deleted', 'Location deleted'), ('invoice.created', 'Invoice created'), ('order.created', 'Order created'), ('order.cancelled', 'Order cancelled'), ('return.created', 'Return processed'), ('purchase.created', 'Purchase order created'), ('purchase.cancelled', 'Purchase order cancelled'), ('payment.recorded', 'Payment recorded'), ('expense.created', 'Expense created'), ('expense.updated', 'Expense updated'), ('expense.deleted', 'Expense deleted'), ('user.created', 'User created'), ('user.updated', 'User updated'), ('user.deactivated', 'User deactivated'), ('user.reactivated', 'User reactivated'), ('settings.updated', 'Business settings updated'), ('backup.triggered', 'Database backup triggered')], max_length=32)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="{field: {'old': ..., 'new': ...}} for an update.")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='accounts_au_action_89571c_idx'), models.Index(fields=['content_type', 'object_id'], name='accounts_au_content_df9335_idx')],
            },
        ),
    ]
