# Generated by Django 5.2.17 on 2026-09-11 11:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('products', '0004_labelbatch_labelbatchitem'),
        ('sales', '0002_salelineunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('condition', models.CharField(choices=[('PENDING', 'Pending inspection'), ('RESELLABLE', 'Resellable'), ('DAMAGED', 'Damaged')], db_index=True, default='PENDING', max_length=12)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='billing.return')),
                ('sale_line_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_units', to='sales.salelineunit')),
                ('serialized_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_units', to='products.serializedunit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
