# Generated by Django 5.2.17 on 2026-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_return_returnunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedelivery',
            name='recipient',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
